### ISSUE TITLE
Crash SDK Initialization

### ISSUE THREAD

**Issue by mauro-poq** [paypal/android-checkout-sdk#101]
Hey, I have 8 crashes in my Crashlytics regarding the SDK initialization, I checked my code and all looks fine from my side as I'm initializing it as described in the documentation. 
It is mainly happening in 3 phones (Pixel 5, Pixel 6 and a GCE x86 phone):
- Pixel 6 ( 1 occurrence ):
![image](https://user-images.githubusercontent.com/59827478/164700013-22e04a14-8873-4523-ab8f-00f9e0fcf761.png)
- Pixel 5 ( 4 occurrences ):
![image](https://user-images.githubusercontent.com/59827478/164700151-39588e6d-4c10-45d3-a2b2-3bf453c6f9b7.png)
- GCE x86 phone ( 3 occurrences ):
![image](https://user-images.githubusercontent.com/59827478/164700238-3ecb6002-eb8d-4c78-95c2-f8e1d3ced226.png)

I'm putting the stack trace below:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.follow.ElfCosmetics/com.paypal.pyplcheckout.home.view.activities.PYPLInitiateCheckoutActivity}: java.lang.IllegalStateException: Required value was null.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 Caused by java.lang.IllegalStateException: Required value was null.
       at com.paypal.pyplcheckout.di.SdkComponent$Companion.getInstance(SdkComponent.kt:74)
       at com.paypal.pyplcheckout.di.SdkComponent.getInstance(SdkComponent.kt:2)
       at com.paypal.pyplcheckout.model.DebugConfigManager.getButtonVersion(DebugConfigManager.java:408)
       at com.paypal.pyplcheckout.instrumentation.InstrumentationEvent$InstrumentationEventBuilder.build(InstrumentationEvent.kt:141)
       at com.paypal.pyplcheckout.instrumentation.PLog.createBuilder(PLog.kt:390)
       at com.paypal.pyplcheckout.instrumentation.PLog.transition(PLog.kt:128)
       at com.paypal.pyplcheckout.instrumentation.PLog.transition$default(PLog.kt:124)
       at com.paypal.pyplcheckout.instrumentation.PLog.transition(PLog.kt:24)
       at com.paypal.pyplcheckout.home.view.BaseActivity.onCreate(BaseActivity.java:62)
       at com.paypal.pyplcheckout.home.view.activities.PYPLInitiateCheckoutActivity.onCreate(PYPLInitiateCheckoutActivity.java:58)
       at android.app.Activity.performCreate(Activity.java:7994)
       at android.app.Activity.performCreate(Activity.java:7978)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Sadly I was not able to reproduce it using a Pixel 6 and a Pixel 4 that I have, let me know if any other info is needed or if I can do something to help.

**Comment by ctamura** [comment]
Can you answer the following

- Is the crash occurring in sandbox and/or live environment?
- SDK Version
- Reproduction steps
