### ISSUE TITLE
Android crashes after login

### ISSUE THREAD

**Issue by MiloszFilimowski** [paypal/android-checkout-sdk#103]
**Describe the bug**
After the autorization with external web client the app crashes, probably related to proguard minification. 
We fixed the initialization crash with:
```
-keepclassmembers class * extends com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite {
  <fields>;
}
```
but unfortunately now it crashes just after returning to the app. This issue only occurs with release builds.

**To Reproduce**
1. Initialize paypal with `PayPalCheckout.setConfig...`
2. Register callbacks with `PayPalCheckout.registerCallbacks`, 
3. Call `PayPalCheckout.startCheckout...`
4. The apps goes to web browser to login
5. After returning, the app crashes with:

```
2022-04-25 13:48:57.641 14099-14099/? E/InstrumentationErr: Error Parsing Experiment fetchAndHandleExperiments()
    java.lang.Exception: Error Parsing Experiment
        at com.paypal.pyplcheckout.ab.elmo.Elmo.fetchRemoteTreatment(SourceFile:16)
        at com.paypal.pyplcheckout.ab.elmo.Elmo.access$fetchRemoteTreatment(SourceFile:1)
        at com.paypal.pyplcheckout.ab.elmo.Elmo$getTreatmentRemote$1.invokeSuspend(SourceFile:4)
        at kotlin.coroutines.jvm.internal.a.resumeWith(SourceFile:4)
        at kotlinx.coroutines.DispatchedTask.run(SourceFile:22)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(SourceFile:2)
        at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:4)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:4)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:1)
2022-04-25 13:49:02.855 14099-14099/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp.development, PID: 14099
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: org.json.b: Unterminated string at character 57
        at org.json.e.g(SourceFile:1)
        at org.json.e.e(SourceFile:14)
        at org.json.e.f(SourceFile:15)
        at org.json.c.<init>(SourceFile:14)
        at org.json.c.<init>(SourceFile:38)
        at com.paypal.pyplcheckout.services.api.CancelUrlApi.createService(SourceFile:5)
        at com.paypal.pyplcheckout.services.api.BaseApi.enqueueRequest(SourceFile:5)
        at com.paypal.pyplcheckout.services.Repository.fetchCancelURL(SourceFile:1)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.fetchCancelURL(SourceFile:1)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.doAfterAuth(SourceFile:9)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.lambda$new$3(SourceFile:1)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.q(Unknown Source:0)
        at com.paypal.pyplcheckout.home.viewmodel.o.invoke(Unknown Source:4)
        at com.paypal.pyplcheckout.auth.AuthHandler$authSuccess$1.invoke(SourceFile:3)
        at com.paypal.pyplcheckout.auth.AuthHandler$authSuccess$1.invoke(SourceFile:1)
        at com.paypal.checkout.createorder.CreateOrderActions.set(SourceFile:2)
        at com.myapp.packages.paypal.PayPalModule$d.b(SourceFile:1)
        at com.myapp.packages.paypal.PayPalModule$d.invoke(SourceFile:1)
        at com.paypal.checkout.createorder.CreateOrder$Companion$invoke$1.create(SourceFile:1)
        at com.paypal.pyplcheckout.auth.AuthHandler.authSuccess(SourceFile:18)
        at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth$2.completeWithSuccess(SourceFile:2)
        at el.c$a.onReceive(Unknown Source:55)
        at h2.a.a(SourceFile:12)
        at h2.a$a.handleMessage(SourceFile:3)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2022-04-25 13:49:03.024 2033-2138/? E/InputDispatcher: channel '69632ad com.myapp.development/com.paypal.pyplcheckout.home.view.activities.PYPLHomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2022-04-25 13:49:03.024 2033-2138/? E/InputDispatcher: channel '13d038a com.myapp.development/com.paypal.pyplcheckout.home.view.activities.PYPLInitiateCheckoutActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

```

**Expected behavior**
The app should not crash.

**Smartphone (please complete the following information):**
 - Android Version: 29
 - Device: Emulator, Samsung SM N-950F
 - SDK Version 0.6.1

**Comment by saperi22** [comment]
Hi @MiloszFilimowski, thanks for reporting this!
Could you please provide us with snippets of your integration? Also, how often does this happen - 100% of the time?

**Comment by MiloszFilimowski** [comment]
Hi, thanks for the reply. Yes, it happens 100% of the time. 
Here is our integration snippet (please not that we are using react native so this is just a wrapper, however this should be completely unrelated to the crash)

```
package com.myapp.packages.paypal
import android.app.Application
import android.util.Log
import com.facebook.react.bridge.*
import com.myapp.BuildConfig
import com.paypal.checkout.PayPalCheckout
import com.paypal.checkout.approve.OnApprove
import com.paypal.checkout.cancel.OnCancel
import com.paypal.checkout.config.CheckoutConfig
import com.paypal.checkout.config.Environment
import com.paypal.checkout.createorder.CreateOrder
import com.paypal.checkout.error.OnError

class PayPalModule(context: ReactApplicationContext, val application: Application): ReactContextBaseJavaModule(context) {
  override fun getName() = "PayPal"

  @ReactMethod
  fun setup(clientID: String, returnUrl: String, enviroment: String) {
    val config = CheckoutConfig(
      application = application,
      clientId = clientID,
      environment = if (enviroment == "live") Environment.LIVE else Environment.SANDBOX,
      returnUrl = returnUrl
    )
    PayPalCheckout.setConfig(config)
  }

  @ReactMethod
  fun startOrder(orderId: String, callback: Callback) {
    PayPalCheckout.registerCallbacks(onApprove = OnApprove {
      val data = Arguments.createMap()
      data.putBoolean("success", true)

      callback(null, data)
    }, onCancel = OnCancel {
      val data = Arguments.createMap()
      data.putBoolean("success", false)

      callback(null, data)
    }, onError = OnError { error ->
      val data = Arguments.createMap()
      val errorData = Arguments.createMap()

      errorData.putString("message", error.reason)
      data.putBoolean("success", false)

      callback(errorData, data)
    })

    PayPalCheckout.startCheckout(CreateOrder { actions ->
      actions.set(orderId)
    })
  }
}
```

**Comment by saperi22** [comment]
@MiloszFilimowski can you please confirm the `orderId` you are sending is not empty?
```
PayPalCheckout.startCheckout(CreateOrder { actions ->
      actions.set(orderId)
    })
```

**Comment by MiloszFilimowski** [comment]
Yes, I can confirm it's not empty. We've checked this several times.

**Comment by saperi22** [comment]
I was unable to reproduce the crash.
While we investigate this further, would you please try version 0.6.2 to check if you still see the bug?

**Comment by MiloszFilimowski** [comment]
Do you have proguard enabled with `minifyEnabled` ? We fixed the crash with the following rules:
```
-keepclassmembers class * extends com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite {
  <fields>;
}

-keep class org.json.** { *; }
```

**Comment by saperi22** [comment]
Yes, I had the `minifyEnabled` flag set.
Thank you for figuring out the proguard rule that worked for you. We'll try to get it in into the next release.
