### ISSUE TITLE
i have issue when login paypal in android 12 app will crush but any other device perfectly work

### ISSUE THREAD

**Issue by praveenpkandroid** [paypal/android-checkout-sdk#125]
V/nxoBaseCallback: https://www.paypal.com/xoplatform/logger/api/logger returned with response
D/BaseSecureKeyWrapper: Base64+URL Safe String: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8aIEvNNHu4tESnkHXC6eVcFDkrz3QbWcctek0lCPgLI4_9in5I8SP8N_pCGGpfze6yLi9WWvz6QuBbB8WWlDog
D/BaseSecureKeyWrapper: Base64+URL Safe String: MEUCIQDK3uHGSoBPpGZoQBGybb8qtk3sl4f39dVZqSPBdLQ4_AIgV8byxNX0_d9wEqJ3Fzhyq7TH7aYk0qCYOBCJrCeAtaU
D/BaseSecureKeyWrapper: encoded Signature String: MEUCIQDK3uHGSoBPpGZoQBGybb8qtk3sl4f39dVZqSPBdLQ4_AIgV8byxNX0_d9wEqJ3Fzhyq7TH7aYk0qCYOBCJrCeAtaU
I/libPerfCtl: fbcNotifySwapBuffers ret=0
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.homechefs.android, PID: 5775
    java.lang.IllegalArgumentException: com.homechefs.android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
        at com.paypal.authcore.authentication.Authenticator.a(Unknown Source:184)
        at com.paypal.authcore.authentication.Authenticator.authenticateForAccessTokenWithDelegate(Unknown Source:96)
        at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth.getUserAccessToken(ThirdPartyAuth.java:140)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.logInUser(MainPaysheetViewModel.java:1285)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.lambda$gzn7IQlqWzbNXDntwRSNZFJjIRk(Unknown Source:0)
        at com.paypal.pyplcheckout.home.viewmodel.-$$Lambda$MainPaysheetViewModel$gzn7IQlqWzbNXDntwRSNZFJjIRk.onUpdateClientConfig(Unknown Source:2)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.lambda$updateClientConfigBefore$17(MainPaysheetViewModel.java:623)
        at com.paypal.pyplcheckout.home.viewmodel.-$$Lambda$MainPaysheetViewModel$qmrZaz53ngvOx8FC6ZinPCiEEac.onEvent(Unknown Source:2)
        at com.paypal.pyplcheckout.events.Events.fire(Events.java:109)
        at com.paypal.pyplcheckout.services.callbacks.ClientConfigUpdateCallback.onApiSuccess(ClientConfigUpdateCallback.kt:54)
        at com.paypal.pyplcheckout.services.callbacks.BaseCallback.onResponse(BaseCallback.kt:38)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
D/OOMEventManagerFK: checkEventAndDumpForJE: 0
I/libPerfCtl: fbcNotifySwapBuffers ret=0
I/Process: Sending signal. PID: 5775 SIG: 9

**Comment by GraceHuntley** [comment]
Can you please share the paypalcheckout sdk version you are using?

Thank you,

**Comment by GraceHuntley** [comment]
Thank you for your response, 0.2.0 is quite old. 0.6.3 is the most recent
version that does not have major implementation changes. 0.7.2 was just
released as well and new documentation for it is on the way soon.

**Comment by praveenpkandroid** [comment]
ok @GraceHuntley  thanks for reply it's fixed
