### ISSUE TITLE
NullPointer getting phone challenge data in Sandbox

### ISSUE THREAD

**Issue by joornby-angel** [paypal/android-checkout-sdk#140]
**Describe the bug**
I'm getting a null pointer in the SDK library after entering my sandbox user email in the login menu.  The stack trace suggests that the challenge data retrieved for the user is null.

**To Reproduce**
1. Launch PayPal programmatically
2. Enter email of sandbox personal account
3. Click "Next"
4. Application crashes

**Expected behavior**
To login

**Screenshots**
I'd produce more, but I don't think that a screenshot of my home page after the crash is very useful.

![image](https://user-images.githubusercontent.com/108282304/188739533-4ec76fed-53d2-4386-a4b2-181f4c67cd73.png)

**Smartphone (please complete the following information):**
 - Android Version: API32
 - Device: Emulator / Nokia x100
 - Browser: Chrome
 - SDK Version: 0.8.0

**Additional context**
Not super sure if I have something configured incorrectly, but here is the stack trace I'm getting: 

```
09-06 17:16:14.832  4574  4574 E AndroidRuntime: java.lang.NullPointerException
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at com.paypal.android.platform.authsdk.splitlogin.domain.ChallengeData.getPhones(Unknown Source:3)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at com.paypal.android.platform.authsdk.otplogin.ui.OTPLoginHandler.isAutoSMSEnabled(SourceFile:187)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at com.paypal.android.platform.authsdk.otplogin.ui.OTPLoginHandler.handleChallenge(SourceFile:50)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at com.paypal.android.platform.authsdk.splitlogin.ui.SplitLoginHandler$handleChallenge$$inlined$suspendCancellableCoroutine$lambda$1$1$2.invokeSuspend(SourceFile:117)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:106)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-06 17:16:14.832  4574  4574 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
````

**Comment by ChrisGuzman** [comment]
Hello,

Can you check if your sandbox user has any phone numbers associated with the account? If you can share the email address or account ID of the account you're using to login that would be helpful as well.

**Comment by joornby-angel** [comment]
@ChrisGuzman Thanks for getting back to me. 

Sandbox account: sb-vbg5820471363@business.example.com

Sandbox user trying to log in:
email: jo.ornby@gmail.com
account id: SH6QULLTXDABL
phone number: 4088935633 (auto-assigned, not mine, and i don't seem to have the capacity to edit it.)
status: verified
country: US

We're doing a programmatic start of the checkout process, relevant code follows:

```
      PayPalCheckout.setConfig(new CheckoutConfig(
        this,
        "XXXXX",
        Environment.SANDBOX,
        BuildConfig.APPLICATION_ID + "://paypalpay",
        CurrencyCode.USD,
        UserAction.PAY_NOW
      ));
```

```
CreateOrder createOrder = createOrderActions -> {
      AppContext context = new AppContext(null, null, "The Chosen", null, null, null, UserAction.PAY_NOW);

      List<PurchaseUnit> units = new ArrayList<>();

      units.add(new PurchaseUnit(
        "referenceId",
        null,
        null,
        "customId",
        null,
        null,
        null,
        new Amount(CurrencyCode.USD, "150", null)
      ));

      Order order = new Order(
        OrderIntent.CAPTURE,
        context,
        units
      );

      createOrderActions.create(order, s -> {});
    };
    
    PayPalCheckout.startCheckout(createOrder);
```

Also to note, I got the iOS SDK working in the sandbox environment prior to working with the Android SDK.

**Comment by joornby-angel** [comment]
Also to note, I wasn't sure how active this github repository was, so I also opened a support ticket on your sales force instance.  The ticket number is: 11322358.

**Comment by ChrisGuzman** [comment]
Thank you. We're investigating.

**Comment by ChrisGuzman** [comment]
@joornby-angel are you minifying your build? Could you try to recreate the error without minifying your build?

**Comment by joornby-angel** [comment]
@ChrisGuzman Hey, I'm just now getting back to this.  I'm no longer able to replicate this issue.  I was not able to test your minification theory, but we are minifying our build.  Is there anything you want me to try to do before we close this issue?

**Comment by applegb** [comment]
@ChrisGuzman, @joornby-angel and I are actually working on same team.
I am seeing this issue as well while testing live environment, not sandbox environment -> 

```
java.lang.NullPointerException
        at com.paypal.android.platform.authsdk.splitlogin.domain.ChallengeData.getPhones(Unknown Source:3)
        at com.paypal.android.platform.authsdk.otplogin.ui.OTPLoginHandler.isAutoSMSEnabled(SourceFile:187)
        at com.paypal.android.platform.authsdk.otplogin.ui.OTPLoginHandler.handleChallenge(SourceFile:50)
        at com.paypal.android.platform.authsdk.splitlogin.ui.SplitLoginHandler$handleChallenge$$inlined$suspendCancellableCoroutine$lambda$1$1$2.invokeSuspend(SourceFile:117)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
        at kotlinx.coroutines.DispatchedTask.run(SourceFile:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException
```

I have tried, un-minifying the code and had the same result.

**Device:** Pixel 6
**Android API:** 33
**SDK Version:** 0.8.1

**Comment by applegb** [comment]
Note for above: If I disable Proguard, the app crashes when it tries to launch the paypal screens (before being presented with login).

```
    java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"
        at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
        at com.paypal.pyplcheckout.home.view.fragments.HomeFragment.onActivityCreated(HomeFragment.kt:229)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3028)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:578)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
        at android.app.Activity.performStart(Activity.java:8315)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3701)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by joornby-angel** [comment]
@ChrisGuzman We're getting this error consistently on a device running Android 13.  Do you have any ideas about what next steps we should take?

**Comment by applegb** [comment]
@ChrisGuzman Any chance you've seen above?

**Comment by joornby-angel** [comment]
Most recent updates to the library have resolved our issue.
