### ISSUE TITLE
Unable to create the LSAT Token for the given Client ID:

### ISSUE THREAD

**Issue by windowschares** [paypal/android-checkout-sdk#141]
I am trying to integrate paypal payment with server implementation on app called DOOO Movie streaming app. when i process the payment page, it crashes and shows following error

2022-09-07 20:02:11.656 28191-28696/com.dooo.android E/InstrumentationErr: Unable to create the LSAT Token for the given Client ID: Adia2dKP9roVwsMssadQc9mTgnARregGcOIUpxQk6kEiPWDfKYDqecirFeLCGCWUqhOnEYwzfrftl1Ud Create LSAT response body did not contain access_token.
    com.paypal.checkout.merchanttoken.CreateLsatTokenException: Unable to create the LSAT Token for the given Client ID: Adia2dKP9roVwsMssadQc9mTgnARregGcOIUpxQk6kEiPWDfKYDqecirFeLCGCWUqhOnEYwzfrftl1Ud
        at com.paypal.checkout.merchanttoken.CreateLsatTokenAction.execute(CreateLsatTokenAction.kt:51)
        at com.paypal.checkout.merchanttoken.CreateLsatTokenAction$execute$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: org.json.JSONException: No value for access_token
        at org.json.JSONObject.get(JSONObject.java:399)
        at org.json.JSONObject.getString(JSONObject.java:560)
        at com.paypal.checkout.merchanttoken.CreateLsatTokenAction.execute(CreateLsatTokenAction.kt:49)
        at com.paypal.checkout.merchanttoken.CreateLsatTokenAction$execute$1.invokeSuspend(Unknown Source:14) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) 
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
2022-09-07 20:02:11.697 28191-28191/com.dooo.android E/InstrumentationErr: order api failed exception when creating order: Unable to create the LSAT Token for the given Client ID: Adia2dKP9roVwsMssadQc9mTgnARregGcOIUpxQk6kEiPWDfKYDqecirFeLCGCWUqhOnEYwzfrftl1Ud
    com.paypal.pyplcheckout.exception.PYPLException: exception when creating order: Unable to create the LSAT Token for the given Client ID: Adia2dKP9roVwsMssadQc9mTgnARregGcOIUpxQk6kEiPWDfKYDqecirFeLCGCWUqhOnEYwzfrftl1Ud
        at com.paypal.checkout.createorder.CreateOrderActions$createOrder$1.invokeSuspend(CreateOrderActions.kt:136)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
2022-09-07 20:04:27.435 29633-30286/com.dooo.android E/InstrumentationErr: Unable to create the LSAT Token for the given Client ID: Adia2dKP9roVwsMssadQc9mTgnARregGcOIUpxQk6kEiPWDfKYDqecirFeLCGCWUqhOnEYwzfrftl1Ud Create LSAT response body did not contain access_token.
    com.paypal.checkout.merchanttoken.CreateLsatTokenException: Unable to create the LSAT Token for the given Client ID: Adia2dKP9roVwsMssadQc9mTgnARregGcOIUpxQk6kEiPWDfKYDqecirFeLCGCWUqhOnEYwzfrftl1Ud
        at com.paypal.checkout.merchanttoken.CreateLsatTokenAction.execute(CreateLsatTokenAction.kt:51)
        at com.paypal.checkout.merchanttoken.CreateLsatTokenAction$execute$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: org.json.JSONException: No value for access_token
        at org.json.JSONObject.get(JSONObject.java:399)
        at org.json.JSONObject.getString(JSONObject.java:560)
        at com.paypal.checkout.merchanttoken.CreateLsatTokenAction.execute(CreateLsatTokenAction.kt:49)
        at com.paypal.checkout.merchanttoken.CreateLsatTokenAction$execute$1.invokeSuspend(Unknown Source:14) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) 
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
2022-09-07 20:04:27.512 29633-29633/com.dooo.android E/InstrumentationErr: order api failed exception when creating order: Unable to create the LSAT Token for the given Client ID: Adia2dKP9roVwsMssadQc9mTgnARregGcOIUpxQk6kEiPWDfKYDqecirFeLCGCWUqhOnEYwzfrftl1Ud
    com.paypal.pyplcheckout.exception.PYPLException: exception when creating order: Unable to create the LSAT Token for the given Client ID: Adia2dKP9roVwsMssadQc9mTgnARregGcOIUpxQk6kEiPWDfKYDqecirFeLCGCWUqhOnEYwzfrftl1Ud
        at com.paypal.checkout.createorder.CreateOrderActions$createOrder$1.invokeSuspend(CreateOrderActions.kt:136)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

**Comment by sterlingann** [comment]
@windowschares  do you mind sharing what version you are on?

**Comment by ChrisGuzman** [comment]
@windowschares I believe you are using the Client ID for a live application while the SDK is set to `Environment.SANDBOX`. Please try again using the Client ID for a sandbox application or setting the the environment to `Environment.LIVE` via

```
        PayPalCheckout.setConfig(
            checkoutConfig = CheckoutConfig(
                environment = Environment.LIVE,
                ...)
```

**Comment by windowschares** [comment]
@sterlingann 
 implementation('com.paypal.checkout:android-sdk:0.6.3')
currently using 9..3

**Comment by windowschares** [comment]
![photo_2022-09-09_09-43-41](https://user-images.githubusercontent.com/88431076/189270590-36ba41c4-43de-4d61-9d55-4c897fed93bd.jpg)
@ChrisGuzman  after trying with your suggestion login page came but after that i got this scope issue attaching screenshot

**Comment by windowschares** [comment]
I think attaching link of error page with logcat will helpful so here is it
[https://www.paypal.com/connect/?redirect_uri=com.dooo.android%3A%2F%2Fpaypalpay&client_id=Adia2dKP9roVwsMssadQc9mTgnARregGcOIUpxQk6kEiPWDfKYDqecirFeLCGCWUqhOnEYwzfrftl1Ud&response_type=code&state=N7a7ny8CqpvQHt-75X8zWQ&scope=openid%20email%20profile%20https%3A%2F%2Furi.paypal.com%2Fweb%2Fexperience%2Fincontextxo&code_challenge=MEUCIAhbGgEN8COY7yCrdJzdjqZRg6Cmku-CMqrgNBKZKIOzAiEAluzz9HxqXtfDORQBKLUsa7msijTzFDdYd0U9zpIhIJo&code_challenge_method=ES256](url)

**Comment by windowschares** [comment]
`E/InstrumentationErr: Error Parsing Experiment fetchAndHandleExperiments()
    java.lang.Exception: Error Parsing Experiment
        at com.paypal.pyplcheckout.ab.elmo.Elmo.fetchRemoteTreatment(Elmo.kt:101)
        at com.paypal.pyplcheckout.ab.elmo.Elmo.access$fetchRemoteTreatment(Elmo.kt:25)
        at com.paypal.pyplcheckout.ab.elmo.Elmo$getTreatmentRemote$1.invokeSuspend(Elmo.kt:78)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
E/nxoEvents: fire: No one listening to the event of type INSTRUMENTATION_SENT.
E/nxoEvents: fire: No one listening to the event of type INSTRUMENTATION_SENT.`

**Comment by ChrisGuzman** [comment]
@windowschares can you confirm that you have entered a return url and added the Full name and Email scopes as outlined in [Enable the SDK instructions](https://developer.paypal.com/limited-release/paypal-mobile-checkout/android/#link-enablethesdk). If you have those can you please share the returnUrl you've set in the `PayPalCheckout.setConfig` method and on the developer dashboard?

**Comment by tdchow** [comment]
Hi @windowschares  - I'm going to close this issue due to inactivity. Please comment here if you're still seeing issues. Thanks!
