### ISSUE TITLE
IllegalStateException attempting multiple checkouts in one application session

### ISSUE THREAD

**Issue by joornby-angel** [paypal/android-checkout-sdk#147]
**Describe the bug**
In a react-native android application, multiple calls to startCheckout result in a crash due to attempting to authenticate with a disposed openid auth service.

**To Reproduce**
1. Programmatically launch a checkout process
2. Complete payment
3. Programmatically launch the checkout process again

**Screenshots**
```
09-19 16:32:03.782 31576 31933 E AndroidRuntime: java.lang.IllegalStateException: Service has been disposed and rendered inoperable
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.paypal.openid.AuthorizationService.a(Unknown Source:9)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.paypal.openid.AuthorizationService.performTokenRequest(Unknown Source:0)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.paypal.openid.AuthorizationService.performTokenRequest(Unknown Source:2)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.paypal.authcore.authentication.Authenticator.a(Unknown Source:243)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.paypal.authcore.authentication.Authenticator.authenticateForAccessTokenWithDelegate(Unknown Source:91)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.paypal.pyplcheckout.flavorauth.WebBasedAuthAccessTokenUseCase.invoke(SourceFile:87)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth.getWebBasedAuthAccessToken(SourceFile:146)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth.access$getWebBasedAuthAccessToken(SourceFile:30)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth$getUserAccessToken$1.onResponse(SourceFile:113)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.paypal.pyplcheckout.ab.elmo.Elmo$getTreatmentRemote$1$1.invokeSuspend(SourceFile:80)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:106)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-19 16:32:03.782 31576 31933 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Smartphone (please complete the following information):**
 - Android Version: API32
 - Device: Emulator
 - Browser: Chrome
 - SDK Version: 0.8.0
 - Package name: com.vidangel.thechosen
 - Client ID: AQJPXia0Q2X8mJp-XPnCRjfmzgP7bveMAwpydlynZ8OXBXD2ewncDjgjniMgEBvm2qppcF8tHsKM4r2X

**Additional context**
- I attempted to update to 0.8.1 but I'm getting a read timeout on the maven repository.
```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.paypal.checkout:android-sdk:0.8.1.
     Required by:
         project :app
      > Could not resolve com.paypal.checkout:android-sdk:0.8.1.
         > Could not get resource 'https://jcenter.bintray.com/com/paypal/checkout/android-sdk/0.8.1/android-sdk-0.8.1.module'.
            > Could not HEAD 'https://jcenter.bintray.com/com/paypal/checkout/android-sdk/0.8.1/android-sdk-0.8.1.module'.
               > Read timed out
```
- Programmatic start relevant code:
```
@ReactMethod
  public void startCheckout(ReadableMap request, Promise promise) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
      promise.reject("NOT_AVAILABLE", new Error());
      return;
    }

    Log.i("PayPal", "action=startCheckout");
    PayPalCheckout.startCheckout(createOrderActions -> {
      AppContext context = new AppContext.Builder().userAction(UserAction.PAY_NOW).build();

      List<PurchaseUnit> units = new ArrayList<>();

      CurrencyCode currencyCode = CurrencyCode.valueOf(request.getString("currency").toUpperCase());
      String amount = String.valueOf(request.getDouble("amount"));

      units.add(new PurchaseUnit(
        new Amount(currencyCode, amount, null)
      ));

      Order order = new Order(
        OrderIntent.CAPTURE,
        context,
        units
      );

      createOrderActions.create(order, orderId -> {
        PayPalCheckout.registerCallbacks(approval -> {
            WritableMap result = new WritableNativeMap();
            result.putString("id", orderId);

            promise.resolve(result);
          },
          null,
          () -> {
            promise.reject(new Error());
          },
          errorInfo -> {
            promise.reject(errorInfo.getError());
          });
      });
    });
  }
  ```

**Comment by WaqarAslam1000** [comment]
Facing the same error

**Comment by JAiden78** [comment]
upgading to SDK Version: 0.8.1 resolved my issue

**Comment by joornby-angel** [comment]
I was able to upgrade to 0.8.1, and can also confirm it's fixed.  Closing this issue.
