### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by LZHIQI** [paypal/android-checkout-sdk#151]
com.paypal.checkout.order.OrderContextNotAvailableException: Tried to retrieve OrderContext before it was created.
        at com.paypal.checkout.order.OrderContext$Companion.get(OrderContext.kt:29)
        at com.paypal.checkout.order.UpdateOrderStatusAction$execute$orderContext$1.invokeSuspend(UpdateOrderStatusAction.kt:33)
        at com.paypal.checkout.order.UpdateOrderStatusAction$execute$orderContext$1.invoke(Unknown Source:8)
        at com.paypal.checkout.order.UpdateOrderStatusAction$execute$orderContext$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at com.paypal.checkout.order.UpdateOrderStatusAction.execute(UpdateOrderStatusAction.kt:32)
        at com.paypal.checkout.order.CaptureOrderAction$execute$2.invokeSuspend(CaptureOrderAction.kt:21)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b677e92, Dispatchers.Main]

**Comment by mahmoud-turki** [comment]
Hi @LZHIQI,

Thank you for reporting the issue. Please fill out all the required information below to be able to assist you. Unfortunately, I won't be able to do anything with just the stack trace.

Before you create a new issue, please search for similar issues. It's possible somebody has encountered this bug already. **PLEASE REMOVE THIS LINE TO ACKNOWLEDGE THAT AN ISSUE DOESN'T ALREADY EXIST FOR THIS BUG**

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Android Version: [e.g. API 30]
 - Device: [e.g. Emulator or One Plus 9]
 - Browser [e.g. chrome, safari] <- only applicable for app switches or fallback situations
 - SDK Version [e.g. 0.1.0]
 - Package name of your app [e.g. com.example.my_app]
 - Client ID

**Additional context**
Add any other context about the problem here.

**Comment by mahmoud-turki** [comment]
Closing this issue as no additional details were provided. Please feel free to re-open it whenever you have all details needed. Thank you!
