### ISSUE TITLE
SdkComponent.java line 74

### ISSUE THREAD

**Issue by mubarakansari715** [paypal/android-checkout-sdk#159]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.***.app/com.paypal.pyplcheckout.home.view.activities.PYPLInitiateCheckoutActivity}: java.lang.IllegalStateException: Required value was null.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by mahmoud-turki** [comment]
Thank you @mubarakansari715 for reporting the issue. Could you please fill out the required filed so we can help you resolving this issue? It's hard to know what's going on with just stack trace and not knowing if you are setting the configs properly or not.

Before you create a new issue, please search for similar issues. It's possible somebody has encountered this bug already. **PLEASE REMOVE THIS LINE TO ACKNOWLEDGE THAT AN ISSUE DOESN'T ALREADY EXIST FOR THIS BUG**

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Android Version: [e.g. API 30]
 - Device: [e.g. Emulator or One Plus 9]
 - Browser [e.g. chrome, safari] <- only applicable for app switches or fallback situations
 - SDK Version [e.g. 0.1.0]
 - Package name of your app [e.g. com.example.my_app]
 - Client ID

**Additional context**
Add any other context about the problem here.

**Comment by mahmoud-turki** [comment]
Closing this issue as no additional details were provided. Please feel free to re-open it whenever you have all details needed. Thank you!
