### ISSUE TITLE
Application crashes when launched     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_1f1cc91.Offline" 

### ISSUE THREAD

**Issue by sunil553** [paypal/android-checkout-sdk#184]
Android App crashes when integrated with Paypal SDK

In our project we have integrated with latest PayPal SDK version 0.8.7 , After the integration android app starts crashing with below Logs 
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_1f1cc91.Offline"

In our application we are using Jacoco for code coverage we are using below version
jacoco {
 toolVersion = "0.8.7"
}

I suspect this might be some dependency conflict issue kindly help me in sorting this issue .

Android Logs below 

    **Caused by: java.lang.ClassNotFoundException:** Didn't find class "org.jacoco.agent.rt.internal_1f1cc91.Offline" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.jd.jdsports.debug-CqYV0Py-KWszsqllvyaNQg==/base.apk"],nativeLibraryDirectories=[/data/app/com.jd.jdsports.debug-CqYV0Py-KWszsqllvyaNQg==/lib/arm64, /data/app/com.jd.jdsports.debug-CqYV0Py-KWszsqllvyaNQg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at

**Comment by dantuswaroop** [comment]
Hi Team,

We are also facing a similar kind of issue,  is there any update on the above please?

**Comment by sunil553** [comment]
Hi Team ,


Any Luck ?

**Comment by tdchow** [comment]
Hey @sunil553 and @dantuswaroop - very sorry for the delayed response. The Jacoco library should be removed in the next release of the SDK. This should prevent this crash.
