### ISSUE TITLE
OrderContextNotAvailableException while capturing payment

### ISSUE THREAD

**Issue by pratikvar** [paypal/android-checkout-sdk#20]
**Describe the bug**
While capturing payment inside `onApprove`, app crashed giving `OrderContextNotAvailableException`

**To Reproduce**
1. Get order id from own server
2. set order id inside `createOrder`
3. complete payment

**Expected behavior**
It should work without crashing

**Smartphone (please complete the following information):**
 - Android Version: Api 29
 - Device: Samsung m31s
 - SDK Version 0.2.0 & 0.3.0

**Additional context**
```
com.paypal.checkout.order.OrderContextNotAvailableException: Tried to retrieve OrderContext before it was created.
        at com.paypal.checkout.order.OrderContext$Companion.get(OrderContext.kt:27)
        at com.paypal.checkout.order.UpdateOrderStatusAction$execute$orderContext$1.invokeSuspend(UpdateOrderStatusAction.kt:27)
        at com.paypal.checkout.order.UpdateOrderStatusAction$execute$orderContext$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:161)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at com.paypal.checkout.order.UpdateOrderStatusAction.execute(UpdateOrderStatusAction.kt:26)
        at com.paypal.checkout.order.CaptureOrderAction$execute$2.invokeSuspend(CaptureOrderAction.kt:21)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by pratikvar** [comment]
Code
```
PayPalCheckout.start(
            createOrder = CreateOrder { createOrderActions ->
                createOrderActions.set(data.data?.order_id ?: "") //assured that order_id will always has some value
            },
            onApprove = OnApprove { approval ->
                Log.e("Paypal", "CaptureOrderResult: $approval")
                approval.orderActions.capture { captureOrderResult ->
                    Log.e("CaptureOrder", "CaptureOrderResult: $captureOrderResult")
                    if(captureOrderResult is CaptureOrderResult.Success)
                        viewModel.onPaymentGatewayResponse(true)
                    else
                        viewModel.onPaymentGatewayResponse(false)
                }
            },
            onCancel = OnCancel {
                Log.e("Paypal", "Buyer canceled the PayPal experience.")
                viewModel.onPaymentGatewayResponse(false)
            },
            onError = OnError {
                Log.e("Paypal", "Error: $it")
                viewModel.onPaymentGatewayResponse(false)
            }
        )
```

**Comment by CodyEngel** [comment]
Hey @pratikvar, it looks like you are trying to capture an order with a token that was generated by your own server. In that case you'd want to also capture the order using your server as well, client-side capture is only supported for orders that are created client-side.

**Comment by pratikvar** [comment]
@CodyEngel Then why same flow works smoothly for IOS?

**Comment by CodyEngel** [comment]
@pratikvar -- the Android SDK took this approach because PayPal supports many different APIs for server-side integrations including: [NVP](https://developer.paypal.com/docs/nvp-soap-api/), [Payments v1](https://developer.paypal.com/docs/api/payments/v1/), [Orders v2](https://developer.paypal.com/docs/api/orders/v2/), there are also third party sales integrations that will call these APIs.

Our client side functionality relies on Orders v2 as it is our newest set of APIs. Given the breadth of possible server-side integrations we opted to only support client side capture/authorize if the token was generated client side as well. If you would like to use client side capture or authorize I would recommend generating the token client side.
