### ISSUE TITLE
Update changelog with required proguard rules for version 0.8.8

### ISSUE THREAD

**Issue by mubarakansari715** [paypal/android-checkout-sdk#205]
--------- beginning of crash
2023-02-15 19:52:00.530 19119-19592/com.alokozayshop.app E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.alokozayshop.app, PID: 19119
    java.lang.IllegalAccessError: Method 'void com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.h(com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel)' is inaccessible to class 'gg0' (declaration of 'gg0' appears in /data/app/~~kEgzQGVmi8zWzzvyxRTACA==/com.alokozayshop.app-7q7SWRYIASEtsB4dFqmO3Q==/base.apk!classes4.dex)
        at gg0.onUpdateClientConfig(SourceFile:1)
        at ig0.onEvent(SourceFile:1)
        at com.paypal.pyplcheckout.events.Events.fire(SourceFile:5)
        at com.paypal.pyplcheckout.services.callbacks.ClientConfigUpdateCallback.onApiSuccess(SourceFile:4)
        at com.paypal.pyplcheckout.services.callbacks.BaseCallback.handleApiSuccess(SourceFile:10)
        at com.paypal.pyplcheckout.services.callbacks.BaseCallback.onResponse(SourceFile:7)
        at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onResponse(SourceFile:3)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

Note: Kindly give a needful solution for this.

**Comment by Mehta2015** [comment]
Yes Even I am facing this issue after updating SDK.

**Comment by mubarakansari715** [comment]
Hello @mahmoud-turki, @tdchow 

Still, I am facing this issue. Can you please upgrade SDK with new pro-guard rules for version

**Comment by mahmoud-turki** [comment]
Hi @Mehta2015, @mubarakansari715 thank you for reporting the issue, please make sure to fill out the template section when you open any issue. We can't reproduce the bug from looking at the logs. Let me know if you have any questions :)

Before you create a new issue, please search for similar issues. It's possible somebody has encountered this bug already. **PLEASE REMOVE THIS LINE TO ACKNOWLEDGE THAT AN ISSUE DOESN'T ALREADY EXIST FOR THIS BUG**

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Android Version: [e.g. API 30]
 - Device: [e.g. Emulator or One Plus 9]
 - Browser [e.g. chrome, safari] <- only applicable for app switches or fallback situations
 - SDK Version [e.g. 0.1.0]
 - Package name of your app [e.g. com.example.my_app]
 - Client ID

**Additional context**
Add any other context about the problem here.
