### ISSUE TITLE
Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by Leheih** [paypal/android-checkout-sdk#212]
**Describe the bug**
Error information collected by firebase：
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.feadoo.lucky/com.paypal.pyplcheckout.home.view.activities.PYPLHomeActivity}: androidx.fragment.app.Fragment$j: Unable to instantiate fragment com.paypal.android.platform.authsdk.splitlogin.ui.SplitLoginFragment: could not find Fragment constructor
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3298)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3437)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)

**To Reproduce**
It should have happened by chance

**Expected behavior**
Handle this error

**Smartphone (please complete the following information):**
 - Android Version: Android 10/Android 11/Android 12
 - Device: TCL REVVL 4 / Schok SV55216 / motorola moto g stylus 5G
 - SDK Version：0.8.6

**Comment by SKPatil2607** [comment]
@Leheih - Any way I can reproduce this issue ?

**Comment by Pannarrow** [comment]
> @Leheih -Can you tell me how many occurrences of this crash ? Also is it only with 0.8.6 version ? did we try updating to latest ?

Brother, did you solve it?

**Comment by Leheih** [comment]
> @Leheih-你能告诉我这次坠机事件发生了多少次吗？它也只有0.8.6版本吗？我们试过更新到最新的吗？

I only used 0.8.6
