### ISSUE TITLE
Crashed when call PayPalCheckout.startCheckout

### ISSUE THREAD

**Issue by Napsterwan** [paypal/android-checkout-sdk#213]
**Describe the bug**
I recently update PayPal Checkout SDK from v0.6.0 to v0.8.8. When I set `minifyEnabled` to false, there is no problem; if set `minifyEnabled` to true, It will crash，when I called `PayPalCheckout.startCheckout`
so, pls update the  proguard rule of SDK

**To Reproduce**
happen all the time

**Additional context**
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chic.point/com.paypal.pyplcheckout.home.view.activities.PYPLHomeActivity}: java.lang.RuntimeException: java.lang.NullPointerException: throw with null exception
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2985)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3120)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: throw with null exception
	at com.paypal.pyplcheckout.di.viewmodel.CustomViewModelFactory.create(SourceFile:7)
	at androidx.lifecycle.ViewModelProvider.get(SourceFile:10)
	at androidx.lifecycle.ViewModelProvider.get(SourceFile:2)
	at com.paypal.pyplcheckout.home.view.activities.PYPLHomeActivity.onCreate(SourceFile:4)
	at android.app.Activity.performCreate(Activity.java:7232)
	at android.app.Activity.performCreate(Activity.java:7221)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3120) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loop(Looper.java:207) 
	at android.app.ActivityThread.main(ActivityThread.java:6878) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
Caused by: java.lang.NullPointerException: throw with null exception
	at com.paypal.authcore.authentication.Authenticator.a(Unknown Source:1)
                                                     authenticateForAccessTokenWithDelegate
                                                     b
	at com.paypal.authcore.authentication.Authenticator.<init>(Unknown Source:41)
	at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuthenticatorProvider.createAuthenticator(SourceFile:21)
	at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth.getAuthenticator(SourceFile:1)
	at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth.<init>(SourceFile:12)
	at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth_Factory.newInstance(SourceFile:1)
	at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth_Factory.get(SourceFile:2)
	at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth_Factory.get(SourceFile:1)
	at com.paypal.pyplcheckout.data.repositories.AuthRepository_Factory.get(SourceFile:2)
	at com.paypal.pyplcheckout.data.repositories.AuthRepository_Factory.get(SourceFile:1)
	at dagger.internal.DoubleCheck.get(SourceFile:6)
	at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel_Factory.get(SourceFile:2)
	at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel_Factory.get(SourceFile:1)
	at com.paypal.pyplcheckout.di.viewmodel.CustomViewModelFactory.create(SourceFile:6)
	at androidx.lifecycle.IIll.Illllllllllllllllllllllllllll(SourceFile:10) 
	at androidx.lifecycle.IIll.Illllllllllllllllllllllllllll(SourceFile:2) 
	at com.paypal.pyplcheckout.home.view.activities.PYPLHomeActivity.onCreate(SourceFile:4) 
	at android.app.Activity.performCreate(Activity.java:7232) 
	at android.app.Activity.performCreate(Activity.java:7221) 
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965) 
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3120) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loop(Looper.java:207) 
	at android.app.ActivityThread.main(ActivityThread.java:6878) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) `

**Comment by glorianetran** [comment]
Hi @Napsterwan thank you for reporting the issue. Can you please elaborate on the steps to reproduce? Also, are you seeing this issue on a specific Android api, or is it the same for all api versions?

Here is a template to fill out to help us better reproduce your issue. 

Before you create a new issue, please search for similar issues. It's possible somebody has encountered this bug already. **PLEASE REMOVE THIS LINE TO ACKNOWLEDGE THAT AN ISSUE DOESN'T ALREADY EXIST FOR THIS BUG**

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Android Version: [e.g. API 30]
 - Device: [e.g. Emulator or One Plus 9]
 - Browser [e.g. chrome, safari] <- only applicable for app switches or fallback situations
 - SDK Version [e.g. 0.1.0]
 - Package name of your app [e.g. com.example.my_app]
 - Client ID

**Additional context**
Add any other context about the problem here.

**Comment by Pannarrow** [comment]
Brother, did you solve it?
