### ISSUE TITLE
Crash when tapping the PayPal button without internet connection

### ISSUE THREAD

**Issue by ghost** [paypal/android-checkout-sdk#217]
**Describe the bug**
If I tap on the PayPal button without an active internet connection it will crash

**To Reproduce**
1. Disable internet connection
2. Click on PayPal button
3. Crash

**Expected behavior**
The application should not crash

**Smartphone (please complete the following information):**
 - Android Version: API 30
 - Device: ONEPLUS 6T
 - SDK Version: 0.8.8
 
**Additional context**
Crash log:
` FATAL EXCEPTION: OkHttp Dispatcher
                                                                                                    Process: com.festool.apps.consumables.qa, PID: 12050
                                                                                                    java.lang.NullPointerException: config.checkoutBaseActivity must not be null
                                                                                                    	at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.fallBackToWeb(PYPLCheckoutUtils.kt:444)
                                                                                                    	at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.fallbackIndefinite(PYPLCheckoutUtils.kt:406)
                                                                                                    	at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.fallBack(PYPLCheckoutUtils.kt:372)
                                                                                                    	at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.fallBack$default(PYPLCheckoutUtils.kt:363)
                                                                                                    	at com.paypal.pyplcheckout.services.callbacks.CancelUrlCallback.cancelUrlFailProtocol(CancelUrlCallback.kt:44)
                                                                                                    	at com.paypal.pyplcheckout.services.callbacks.CancelUrlCallback.onApiError(CancelUrlCallback.kt:21)
                                                                                                    	at com.paypal.pyplcheckout.services.callbacks.BaseCallback.handleApiError(BaseCallback.kt:92)
                                                                                                    	at com.paypal.pyplcheckout.services.callbacks.BaseCallback.onFailure(BaseCallback.kt:42)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)`

**Comment by obamakang** [comment]
03-14 21:32:22.547   766  9861 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-14 21:32:22.547   766  9861 E AndroidRuntime: Process: com.pikcloud.pikpak, PID: 766
03-14 21:32:22.547   766  9861 E AndroidRuntime: java.lang.NullPointerException: config.checkoutBaseActivity must not be null
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.fallBackToWeb(PYPLCheckoutUtils.kt:444)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.fallbackIndefinite(PYPLCheckoutUtils.kt:406)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.fallBack(PYPLCheckoutUtils.kt:372)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.fallBack$default(PYPLCheckoutUtils.kt:363)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at com.paypal.pyplcheckout.services.callbacks.ClientConfigUpdateCallback.clientConfigUpdateFailProtocol(ClientConfigUpdateCallback.kt:54)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at com.paypal.pyplcheckout.services.callbacks.ClientConfigUpdateCallback.onApiError(ClientConfigUpdateCallback.kt:35)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at com.paypal.pyplcheckout.services.callbacks.BaseCallback.handleApiError(BaseCallback.kt:92)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at com.paypal.pyplcheckout.services.callbacks.BaseCallback.onFailure(BaseCallback.kt:42)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onFailure(InstrumentOkHttpEnqueueCallback.java:63)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-14 21:32:22.547   766  9861 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)

**Comment by obamakang** [comment]
i have the same problem

**Comment by zurich37** [comment]
sdk version：1.3.0 also have the same problem...

**Comment by ImVeryGood** [comment]
i have the same problem   version:1.3.0
