### ISSUE TITLE
SDK crash on second order after login

### ISSUE THREAD

**Issue by LorenzoFumagalli** [paypal/android-checkout-sdk#23]
Hi, after the login with a sandbox account the order is confirmed and everything is ok.
While trying to create a new order however the SDK crash with the following

kotlin.UninitializedPropertyAccessException: lateinit property accessToken has not been initialized
        at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.getCheckoutLiteUrl(PYPLCheckoutUtils.kt:239)
        at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.getCheckoutLiteUrl$default(PYPLCheckoutUtils.kt:171)
        at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.fallBackToWeb(PYPLCheckoutUtils.kt:337)
        at com.paypal.pyplcheckout.utils.PYPLCheckoutUtils.fallBack(PYPLCheckoutUtils.kt:311)
        at com.paypal.pyplcheckout.auth.AuthHandler.authFailure(AuthHandler.kt:84)
        at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth$2.completeWithFailure(ThirdPartyAuth.java:122)
        at com.paypal.authcore.authentication.Authenticator$b.onTokenRequestCompleted(Unknown Source:6)
        at com.paypal.openid.AuthorizationService$b.a(Unknown Source:57)
        at com.paypal.openid.AuthorizationService$b.onPostExecute(Unknown Source:2)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

I'm using the last version of the sdk (0.3.1)

**Comment by tdchow** [comment]
Hey @LorenzoFumagalli! Thanks for reporting this issue. 

We're aware of the problem and are currently working on the fix. I'll keep you updated on the status here in this thread.

**Comment by tdchow** [comment]
@LorenzoFumagalli - A server side fix was deployed that should resolve this issue.

In the next release of the SDK we'll have a fix to prevent this crash, but the underlying issue ended up being server side. Please try again with the same version of the SDK and let me know if you see any issues!

**Comment by LorenzoFumagalli** [comment]
Hi @tdchow 

Thanks for your feedback. 
In the next few days I will test it with different configuration and locale since I was able to replicate the same crash on a device with locale in Italy. 

Many thanks

**Comment by tdchow** [comment]
@LorenzoFumagalli - No worries! I'm going to close out this issue, but please reach out if you encounter the issue again.

**Comment by maxczc** [comment]
> @LorenzoFumagalli - No worries! I'm going to close out this issue, but please reach out if you encounter the issue again.

the crash happend to me , the paypal checkout version is 0.3.1

**Comment by tdchow** [comment]
Hey @maxczc! If you're still seeing this crash, would you be able to open a separate issue and share your config/integration information? Would love to help you with your SDK integration 😄
