### ISSUE TITLE
.PYPLInitiateCheckoutActivity}: java.lang.IllegalStateException: Required value was null.

### ISSUE THREAD

**Issue by jmic134** [paypal/android-checkout-sdk#250]
**Describe the bug**
App crashes when start up

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android Version: android 9-13
 - Device: goolge Pixel 5/7
 - SDK Version: com.paypal.checkout:android-sdk:0.112.0
 - Crash probability: 2%

**Additional context**
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.paypal.pyplcheckout.ui.feature.home.activities.PYPLInitiateCheckoutActivity}: java.lang.IllegalStateException: Required value was null.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
```
Caused by java.lang.IllegalStateException: Required value was null.
       at com.paypal.pyplcheckout.di.SdkComponent$Companion.getInstance(:13)
       at com.paypal.pyplcheckout.di.SdkComponentKt.inject(SourceFile:31)
       at com.paypal.pyplcheckout.ui.feature.home.activities.BaseActivity.onCreate(SourceFile:6)
       at com.paypal.pyplcheckout.ui.feature.home.activities.PYPLInitiateCheckoutActivity.onCreate(SourceFile:3)
       at android.app.Activity.performCreate(Activity.java:8305)
       at android.app.Activity.performCreate(Activity.java:8284)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by MaxHastingsPP** [comment]
If you are still running into this issue please provide us with the following information.

- Environment - sandbox or live?
- Screenshots or screen recording
- Steps to reproduce the issue.

Thank you!
