### ISSUE TITLE
Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.e, parameter exception

### ISSUE THREAD

**Issue by jmic134** [paypal/android-checkout-sdk#251]
**Describe the bug**
App crashes when paying

**To Reproduce**
Unable to know the operation path, but know the jump activity
 PYPLInitiateCheckoutActivity>> PYPLHomeActivity>>AuthorizationManagementActivity>> PYPLHomeActivity

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android Version: android 10-13
 - Device: any device
 - SDK Version: com.paypal.checkout:android-sdk:0.112.0
 - Crash probability: 1%

**Additional context**
```
Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.e, parameter exception
       at com.paypal.authcore.authentication.PartnerAuthenticationProvider$authenticateWebLogin$authenticationDelegate$1.completeWithFailure(:2)
       at com.paypal.authcore.authentication.Authenticator$a.onReceive(:174)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(SourceFile:60)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(SourceFile:12)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8399)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by MaxHastingsPP** [comment]
If you are still running into this issue please provide us with the following information.

- Environment - sandbox or live?
- Steps to reproduce the issue.

Thank you!
