### ISSUE TITLE
FATAL EXCEPTION: OkHttp Dispatcher     Process: com.xxx.xxx, PID: 15025     android.content.ActivityNotFoundException         at com.paypal.openid.AuthorizationService.a()

### ISSUE THREAD

**Issue by A-10ng** [paypal/android-checkout-sdk#27]
Action: 
when I click the paypal button , anr shows(Two Nexus phone acts normally, A samsung phone does not behave properly ). 

Logcat: 
FATAL EXCEPTION: OkHttp Dispatcher     Process: com.xxx.xxx, PID: 15025     android.content.ActivityNotFoundException         at com.paypal.openid.AuthorizationService.a()         at com.paypal.openid.AuthorizationService.performAuthorizationRequest()         at com.paypal.authcore.authentication.Authenticator.a()         at com.paypal.authcore.authentication.Authenticator.authenticateForAccessTokenWithDelegate()         at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth.getUserAccessToken(ThirdPartyAuth.java:140)         at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.logInUser(MainPaysheetViewModel.java:1423)         at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.lambda$gzn7IQlqWzbNXDntwRSNZFJjIRk(MainPaysheetViewModel.java)         at com.paypal.pyplcheckout.home.viewmodel.-$$Lambda$MainPaysheetViewModel$gzn7IQlqWzbNXDntwRSNZFJjIRk.onUpdateClientConfig(lambda)         at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.lambda$updateClientConfigBefore$18(MainPaysheetViewModel.java:676)         at com.paypal.pyplcheckout.home.viewmodel.-$$Lambda$MainPaysheetViewModel$7bqLPJINhX0FCLdPicr9f-mb2EU.onEvent(lambda)         at com.paypal.pyplcheckout.events.Events.fire(Events.java:119)         at com.paypal.pyplcheckout.services.callbacks.ClientConfigUpdateCallback.onApiSuccess(ClientConfigUpdateCallback.kt:54)         at com.paypal.pyplcheckout.services.callbacks.BaseCallback.onResponse(BaseCallback.kt:38)         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)         at java.lang.Thread.run(Thread.java:818) 

Phone: 
Samsung SM-G9280, Android 6.0.1, android-checkout-sdk  0.3.1

**Comment by tdchow** [comment]
Hey @A-10ng! Thanks for reporting the issue. A few questions:

* Are you using any code minification tools?
* Does the Samsung phone have the Chrome browser installed? If it doesn't, can you try installing Chrome and retesting the PayPal Checkout SDK? This should help identify the issue.

**Comment by A-10ng** [comment]
1.No minification tools

**Comment by A-10ng** [comment]
1.No minification tools
2.Not work

**Comment by tdchow** [comment]
Can you please provide a list of all the browsers you have installed on that Samsung device? And can you provide the app ids for each?

**Comment by A-10ng** [comment]
Only Google Chrome v12.29.8.23.arm64（Sorry to reply u so late）

**Comment by tdchow** [comment]
Hey @A-10ng - No worries. I spent some time looking into the issue and I've narrowed it down to being an issue with the installed browser(s) on the device. 

Follow-up question - Is there an MDM solution on that Samsung device?

I'm working on a fix that will hopefully resolve the issue.

**Comment by A-10ng** [comment]
No MDM solution

**Comment by tdchow** [comment]
@A-10ng Sorry for the delay. I have a fix that's still waiting for deployment. Will keep you updated.

**Comment by tdchow** [comment]
Hey @A-10ng - This issue should be resolved in the latest version of the SDK. Can you try updating to 0.5.1 and retesting?

**Comment by tdchow** [comment]
Hey @bryanbernardo28 - I believe this is a different issue. This looks like a cause due to support libraries missing when building your project. Could you either try enabling Jetifier (adding `android.enableJetifier=true` to your gradle.properties file) or upgrading to version 0.5.2 of the Checkout SDK? Upgrading to the latest version would be the better solution.

**Comment by tdchow** [comment]
Closing due to inactivity.
