### ISSUE TITLE
General instability/incompatibility with SDK

### ISSUE THREAD

**Issue by developer-dmp** [paypal/android-checkout-sdk#47]
I have imported `com.paypal.checkout:android-sdk:0.1.0` into my project for native deposit flow - running into a number of issues on varying OS levels.

## Implementation Details
We are making use of the [Server-side integration](https://developer.paypal.com/docs/business/native-checkout/android/sdk-server-side/#1-launch-the-payment-sheet). There is no issue with our server implementation in regards to the creation of the orderId that we pass along to the SDK.  As a reference, this is called once we get the orderId from our backend:
```
private fun startPayPalDeposit(paypalOrderId: String) {
        checkoutSdk.start(
            createOrder = CreateOrder { createOrderActions ->
                createOrderActions.set(paypalOrderId)
            },
            onApprove = OnApprove {
                viewModel.capturePaypalDeposit(paypalOrderId)
            },
            onCancel = OnCancel {
                viewModel.onStopLoading()
            },
            onError = OnError {
                viewModel.onStopLoading()
            }
        )
    }
```
For what it is worth, this exact implementation has **no issues** on newer versions of Android, API 26+.

## Running on Android API 21
```
java.lang.RuntimeException: Feature only supported for versions Android-M and above
        at com.paypal.authcore.security.BaseSecureKeyWrapper.generatePublicKey()
        at com.paypal.authcore.security.NoAuthSecureKeyWrapper.generateAsymmetricKeyPair()
        at com.paypal.authcore.authentication.Authenticator.a()
        at com.paypal.authcore.authentication.Authenticator.authenticateForAccessTokenWithDelegate()
        at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth.getUserAccessToken(ThirdPartyAuth.java:140)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.logInUser(MainPaysheetViewModel.java:1036)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.lambda$u3bJQV5CM255mmoJkHAH5Y7Tgzs(MainPaysheetViewModel.java)
        at com.paypal.pyplcheckout.home.viewmodel.-$$Lambda$MainPaysheetViewModel$u3bJQV5CM255mmoJkHAH5Y7Tgzs.onUpdateClientConfig(lambda)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.lambda$updateClientConfigBefore$11(MainPaysheetViewModel.java:394)
        at com.paypal.pyplcheckout.home.viewmodel.-$$Lambda$MainPaysheetViewModel$bZWZcCIiVLiE6wcvi0c3LrRX6pk.onEvent(lambda)
        at com.paypal.pyplcheckout.events.Events.fire(Events.java:109)
        at com.paypal.pyplcheckout.services.callbacks.ClientConfigUpdateCallback.onApiSuccess(ClientConfigUpdateCallback.kt:53)
        at com.paypal.pyplcheckout.services.callbacks.BaseCallback.onResponse(BaseCallback.kt:38)
        at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onResponse(InstrumentOkHttpEnqueueCallback.java:69)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```
This doesn't make sense to me since the CHANGELOG.md only calls out API 23 as the minimum in `Version 0.4.0`.  However, after checking the source code pulled into the project, I can see this:
```
    @TargetApi(23)
    @NonNull
    public PublicKey generatePublicKey(@NonNull String var1, boolean var2)
```

## Running on Android API 23
First, the app will launch the user to the browser to select which payment method they want to use from their account. Then upon selecting one and clicking the Continue button, it will display a loading screen and say something along the lines of "Returning you to XYZ Inc".  When the application returns, this overlay is presented to the user and nothing happens.  The only thing I can find in the logs that might be relevant is this:
`No one listening to the event of type NATIVE_CHECKOUT_PAY_SHEET_LIFE_CYCLE.`

![Screenshot_1630601079](https://user-images.githubusercontent.com/31141114/131884098-a5fc2dd7-4258-478c-970d-0c3f9fab74c3.png)

## Additional notes
If I try to upgrade the library to `com.paypal.checkout:android-sdk:0.2.0` (I also add the necessary info to the project-level build.gradle file), I get this as output when running on API 21:
```
java.lang.RuntimeException: Feature only supported for versions Android-M and above
        at com.paypal.authcore.security.BaseSecureKeyWrapper.generatePublicKey()
        at com.paypal.authcore.security.NoAuthSecureKeyWrapper.generateAsymmetricKeyPair()
        at com.paypal.authcore.authentication.Authenticator.a()
        at com.paypal.authcore.authentication.Authenticator.authenticateForAccessTokenWithDelegate()
        at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth.getUserAccessToken(ThirdPartyAuth.java:140)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.logInUser(MainPaysheetViewModel.java:1285)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.lambda$u3bJQV5CM255mmoJkHAH5Y7Tgzs(MainPaysheetViewModel.java)
        at com.paypal.pyplcheckout.home.viewmodel.-$$Lambda$MainPaysheetViewModel$u3bJQV5CM255mmoJkHAH5Y7Tgzs.onUpdateClientConfig(lambda)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.lambda$updateClientConfigBefore$17(MainPaysheetViewModel.java:623)
        at com.paypal.pyplcheckout.home.viewmodel.-$$Lambda$MainPaysheetViewModel$aNrB20LFlUkv6bj-6UgWWnDtt-A.onEvent(lambda)
        at com.paypal.pyplcheckout.events.Events.fire(Events.java:109)
        at com.paypal.pyplcheckout.services.callbacks.ClientConfigUpdateCallback.onApiSuccess(ClientConfigUpdateCallback.kt:54)
        at com.paypal.pyplcheckout.services.callbacks.BaseCallback.onResponse(BaseCallback.kt:38)
        at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onResponse(InstrumentOkHttpEnqueueCallback.java:69)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```
Again, this is quite annoying since the CHANGELOG.md calls out this library bump in `Version 0.4.0`, but the function is likely annotated like it was in `0.1.0`.

When running `com.paypal.checkout:android-sdk:0.2.0` on API 23, we end up with the same issue as shown above for the same API version (the picture of the transparent Activity over our application) with a bunch of different errors:
```
E/InstrumentationErr: Error Parsing Experiment fetchAndHandleExperiments()
    java.lang.Exception: Error Parsing Experiment
        at com.paypal.pyplcheckout.ab.elmo.Elmo.fetchRemoteTreatment(Elmo.kt:94)
``` 
```
E/InstrumentationErr: java.lang.Exception: Experiment not found in cache fetchAndHandleExperiments()
    java.lang.Exception: Experiment not found in cache
        at com.paypal.pyplcheckout.ab.elmo.Elmo.getTreatment(Elmo.kt:111)
```
```
E/InstrumentationErr: java.lang.Exception: Experiment not found in cache fetchAndHandleExperiments()
    java.lang.Exception: Experiment not found in cache
        at com.paypal.pyplcheckout.ab.elmo.Elmo.getTreatment(Elmo.kt:111)
```
```
E/InstrumentationErr: error in reading UserCheckoutResponse Binary XML file line #11: Binary XML file line #11: Error inflating class ImageView
    android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class ImageView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
```
All of these errors are returned with just a single transaction attempt.

Regardless of what I upgrade the library to, if I update the project to target API 23, a device at that level crashes when pulling up wallet due to: 
```
E/InstrumentationErr: error in reading UserCheckoutResponse Binary XML file line #11: Binary XML file line #11: Error inflating class ImageView
    android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class ImageView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
```
The theme for the project: `Theme.MaterialComponents.DayNight.NoActionBar`.

### Conclusion
There seem to be a handful of issues at lower API levels. Specifically 21 and 23 having issues no matter which library version available. All of these tests ran on emulated Pixel devices with Google Play Services x86 straight from the AVD Manager.  I haven't tested versions 24 and 25 at the moment, so I don't know where the exact floor is, but the same implementation in code works for API level 26, 29, 30 regardless of library version.

**Comment by tdchow** [comment]
@developer-dmp - Thanks for the very detailed description and logs. I think there are a few issues that you're pointing out. Let me try to break them down.

### Requiring Android API 23 and Above
Unfortunately, all versions of the Checkout SDK will require Android API 23 and above. The `generatePublicKey` function always required Android API 23. In version 0.4.0 we marked the external SDK functions to require API 23 to prevent the `java.lang.RuntimeException: Feature only supported for versions Android-M and above` crash.

### Android API 23
This sounds like a deep link issue when the browser tries to come back to your app. Would it be possible to share a screen recording of this flow? Are you also seeing this on later versions of the Checkout SDK?

### InstrumentationErr Logs
Seeing these logs are normal and are caused by AB tests that exist in the SDK. I can check with an internal team that manages that if they can change the log level for these.

### Error inflating class ImageView Crash
Is this crash happening only when your app module targets API 23? We haven't done much testing with targeting unsupported SDK versions.


We recommend that you always use the latest version of the Checkout SDK. There aren't any cases where newer versions remove functionality. Hope this helps and please let me know if you have additional questions.

**Comment by tdchow** [comment]
Closing due to inactivity.
