### ISSUE TITLE
Crash when opening the app after using the proxy（problem with version 0.4.5 bug）

### ISSUE THREAD

**Issue by androidGithubRookie** [paypal/android-checkout-sdk#56]
AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    kotlin.UninitializedPropertyAccessException: lateinit property abManager has not been initialized
        at com.paypal.pyplcheckout.services.callbacks.BaseCallback.retryOnError(BaseCallback.kt:78)
        at com.paypal.pyplcheckout.services.callbacks.BaseCallback.onFailure(BaseCallback.kt:40)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by tdchow** [comment]
Hey @androidGithubRookie - This looks like a duplicate issue of https://github.com/paypal/android-checkout-sdk/issues/53. I'm going to close this out, but please follow the other issue that was created.
