### ISSUE TITLE
IllegalStateException on closing Paypal sign in view

### ISSUE THREAD

**Issue by abedsh** [paypal/android-checkout-sdk#71]
**Describe the bug**
App crashes when closing the Paypal sign in view.  This is only happening when the app's activity is killed due to memory pressure after opening the sign in view

**To Reproduce**
1. To simulate killing the app's activity due to memory pressure, in Settings, under Developer options, check "Don't keep activities"
2. Open the Paypal sign in view in the app
3. Go back, or close it
4. The app crashes with error "Unable to start activity" or "Service has been disposed and rendered inoperable" after seeing the paypal "securely logging you in" dialog

**Expected behavior**
User should be able to close the Paypal sign in page without a crash even if the app's activity was killed by the OS due to memory pressure

**Screenshots**
![Screenshot_20211221-164555](https://user-images.githubusercontent.com/14999961/147002029-abb5f02f-955f-4ba7-8497-5f7be5b27c69.png)
![Screenshot_20211221-181805](https://user-images.githubusercontent.com/14999961/147010237-1535bd31-0a65-4fe8-97cf-8b3beee85bf9.png)

**Smartphone (please complete the following information):**
 - Android Version: API 25
 - Device: LDPlayer Model SM-G965N
 - SDK Version 0.5.2

**Additional context**
Error Stacktrace 1
```
2021-12-21 17:17:53.194 12050-12283/com.yababa.yababapp.dev E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.yababa.yababapp.dev, PID: 12050
    java.lang.IllegalStateException: Service has been disposed and rendered inoperable
        at com.paypal.openid.AuthorizationService.a()
        at com.paypal.openid.AuthorizationService.createCustomTabsIntentBuilder()
        at com.paypal.authcore.authentication.Authenticator.a()
        at com.paypal.authcore.authentication.Authenticator.authenticateForAccessTokenWithDelegate()
        at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth.getUserAccessToken(ThirdPartyAuth.java:149)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.logInUser(MainPaysheetViewModel.java:1629)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.$r8$lambda$u3bJQV5CM255mmoJkHAH5Y7Tgzs(MainPaysheetViewModel.java)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel$$ExternalSyntheticLambda9.onUpdateClientConfig(Unknown Source)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.lambda$updateClientConfigBefore$22(MainPaysheetViewModel.java:818)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel$$ExternalSyntheticLambda0.onEvent(Unknown Source)
        at com.paypal.pyplcheckout.events.Events.fire(Events.java:116)
        at com.paypal.pyplcheckout.services.callbacks.ClientConfigUpdateCallback.onApiSuccess(ClientConfigUpdateCallback.kt:54)
        at com.paypal.pyplcheckout.services.callbacks.BaseCallback.handleApiSuccess(BaseCallback.kt:114)
        at com.paypal.pyplcheckout.services.callbacks.BaseCallback.onResponse(BaseCallback.kt:68)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```
Error Stacktrace 2

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yababa.yababapp/com.paypal.pyplcheckout.home.view.activities.PYPLInitiateCheckoutActivity}: java.lang.IllegalStateException: Required value was null.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3555)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by andrespelaezp** [comment]
Hey @abedsh - Thanks for reporting this.

I'll be helping you out with your issue. 

While I am trying to replicate the crash, could you point me where the second Stacktrace you provided crashed? ( a short code snippet would be very helpful ).

**Comment by abedsh** [comment]
Hey @andrespelaezp, the second stacktrace happens the same way. I couldn't specifically replicate it. Here's a small code snippet if it helps. Thanks!

Paypal payment class being called from a fragment

```
public class PaypalPaymentGatewayProcessor {
    private Boolean useTest;
    private String clientId, sessionId;
    private Activity mActivity;

    public PaypalPaymentGatewayProcessor(Boolean useTest, String clientId, String sessionId, Activity mActivity) {
        this.useTest = useTest;
        this.clientId = clientId;
        this.sessionId = sessionId;
        this.mActivity = mActivity;
        configPaypal();
    }

    private void configPaypal(){
        CheckoutConfig config = new CheckoutConfig(
                mActivity.getApplication(),
                clientId,
                useTest? Environment.SANDBOX : Environment.LIVE,
                String.format("%s://paypalpay", BuildConfig.APPLICATION_ID),
                CurrencyCode.EUR,
                UserAction.PAY_NOW,
                null,
                new SettingsConfig(
                        true,
                        false
                )
        );

        PayPalCheckout.setConfig(config);
    }

    public void createPayment(OnApprove onApprove, OnShippingChange onShippingChange, OnCancel onCancel, OnError onError){
        PayPalCheckout.start(new CreateOrder() {
            @Override
            public void create(@NonNull CreateOrderActions createOrderActions) {
                createOrderActions.set(sessionId);
            }
        }, onApprove,onShippingChange,onCancel,onError);
    }

}
```

the call from the fragment

```
 protected void goToPaypalPayment(String clientId,final String sessionId) {
        PaypalPaymentGatewayProcessor paypalPay = new PaypalPaymentGatewayProcessor(BuildConfig.USE_TEST_PAY, clientId, sessionId, getActivity());
        paypalPay.createPayment(new OnApprove() {
            @Override
            public void onApprove(@NonNull Approval approval) {
                API.paymentSuccess(, response -> {
                  
                }, error -> {
                    setBusy(false);
                
                }, TAG);
            }
        }, null, new OnCancel() {
            @Override
            public void onCancel() {
                setBusy(false);
                cancelReservedOrder(sessionId);
            }
        }, new OnError() {
            @Override
            public void onError(@NonNull ErrorInfo errorInfo) {
                setBusy(false);
                cancelReservedOrder(sessionId);
            }
        });
    }
```

**Comment by andrespelaezp** [comment]
Hey @abedsh, thanks again for reporting this. 

I've been looking into it for a few days and we managed to replicate it, even further, a solution is already proposed and we are reviewing it. I will keep you posted with the updates and future release.

**Comment by abedsh** [comment]
@andrespelaezp thank you

**Comment by tdchow** [comment]
Hi @abedsh - We just released a new version of the SDK (version 0.6.0) which now handles when the app is killed in the background. Can you check to see if the new version resolved the reported crash? Thanks!

```implementation 'com.paypal.checkout:android-sdk:0.6.0'```

**Comment by abedsh** [comment]
@tdchow perfect, thank you

**Comment by tdchow** [comment]
Closing this out due to inactivity. The issue should be resolved in the latest SDK version.
