### ISSUE TITLE
Add FLAG_IMMUTABLE or FLAG_MUTABLE on PendingIntent

### ISSUE THREAD

**Issue by simao-coutinho** [paypal/android-checkout-sdk#84]
When try to pay with Android emulator version API 32 give me this error.
This error not occours on API 30

Appears the logging bottom sheet then the app crashes

![147010237-1535bd31-0a65-4fe8-97cf-8b3beee85bf9](https://user-images.githubusercontent.com/37965258/151539221-9a4cd7c1-2dad-4cac-a7ff-3902566038be.png)

The log error below:

FATAL EXCEPTION: OkHttp Dispatcher
java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
        at com.paypal.authcore.authentication.Authenticator.a(Unknown Source:223)
        at com.paypal.authcore.authentication.Authenticator.authenticateForAccessTokenWithDelegate(Unknown Source:96)
        at com.paypal.pyplcheckout.flavorauth.ThirdPartyAuth.getUserAccessToken(ThirdPartyAuth.java:149)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.logInUser(MainPaysheetViewModel.java:1629)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.$r8$lambda$u3bJQV5CM255mmoJkHAH5Y7Tgzs(Unknown Source:0)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel$$ExternalSyntheticLambda9.onUpdateClientConfig(Unknown Source:2)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel.lambda$updateClientConfigBefore$22(MainPaysheetViewModel.java:818)
        at com.paypal.pyplcheckout.home.viewmodel.MainPaysheetViewModel$$ExternalSyntheticLambda0.onEvent(Unknown Source:2)
        at com.paypal.pyplcheckout.events.Events.fire(Events.java:116)
        at com.paypal.pyplcheckout.services.callbacks.ClientConfigUpdateCallback.onApiSuccess(ClientConfigUpdateCallback.kt:54)
        at com.paypal.pyplcheckout.services.callbacks.BaseCallback.handleApiSuccess(BaseCallback.kt:114)
        at com.paypal.pyplcheckout.services.callbacks.BaseCallback.onResponse(BaseCallback.kt:68)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

**Comment by tdchow** [comment]
Hi @simao-coutinho - We're currently working on a fix for this. It'll be released as a part of the changes for Android 12 (https://github.com/paypal/android-checkout-sdk/issues/67).

**Comment by tdchow** [comment]
Hey @simao-coutinho - We just released version 0.6.0 of the Checkout SDK which now targets Android 12. This should resolve the crash you were seeing.

```implementation 'com.paypal.checkout:android-sdk:0.6.0'```

**Comment by tdchow** [comment]
Closing due to inactivity. @simao-coutinho, let us know if you're still seeing the issue on the latest version of the SDK.
