### ISSUE TITLE
Using the version 0.5.4 App is getting crashed

### ISSUE THREAD

**Issue by pd90** [paypal/android-checkout-sdk#89]
The App has recently started crashing with the following error, though there are no changes in the CheckOut config but getting this recurring internal SDK error, if it is a known issue will a SDK version bump up work, or is there any other way to handle it 
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 11 path $.error
at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
at com.google.gson.Gson.fromJson(Gson.java:932)
at com.google.gson.Gson.fromJson(Gson.java:870)
at com.paypal.checkout.fundingeligibility.RetrieveFundingEligibilityAction$retrieve$3$await$$inlined$suspendCancellableCoroutine$lambda$1.onResponse(NetworkExtensions.kt:25)
at

**Comment by tdchow** [comment]
Hey @pd90 - Thanks for reporting this issue. I'm currently looking into the issue. In the meantime, could you please share snippets of your integration?

**Comment by tdchow** [comment]
Hi @pd90 - Can you try your integration again? There was an issue with one of the API calls returning a different structure. This should be resolved now. Please let me know if you're still seeing issues!

**Comment by pd90** [comment]
Hi @tdchow thanks for the update, i will redo integration

**Comment by tdchow** [comment]
Closing this issue out. @pd90 - we can reopen the issue if you're still seeing the crash. Thanks!
