### ISSUE TITLE
NoSuchMethodException in Android 5 (API 21)

### ISSUE THREAD

**Issue by elkarry** [paypal/android-checkout-sdk#94]
When starting the SDK with setConfig in Android 5 it produces a NoSuchMethodException.
This error occurs on API 21 with te latest SDK version 0.6.0

Log error below:

Fatal Exception: java.lang.NoSuchMethodError: No virtual method getSystemService(Ljava/lang/Class;)Ljava/lang/Object; in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar)
       at com.paypal.pyplcheckout.network.ConnectivityHandler.<init>(ConnectivityHandler.kt:55)
       at com.paypal.pyplcheckout.network.ConnectivityHandler_Factory.newInstance(ConnectivityHandler_Factory.java:40)
       at com.paypal.pyplcheckout.network.ConnectivityHandler_Factory.get(ConnectivityHandler_Factory.java:30)
       at com.paypal.pyplcheckout.network.ConnectivityHandler_Factory.get(ConnectivityHandler_Factory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.paypal.pyplcheckout.di.DaggerSdkComponent.getConnectivityHandler(DaggerSdkComponent.java:330)
       at com.paypal.pyplcheckout.di.SdkComponent$Companion.initEagerSingletons(SdkComponent.kt:79)
       at com.paypal.pyplcheckout.di.SdkComponent$Companion.create(SdkComponent.kt:68)
       at com.paypal.checkout.PayPalCheckout.setConfig(PayPalCheckout.kt:68)

Device
Galaxy Tab4 10.1
Android version
5.0.2
SDK version
0.6.0

**Comment by ndmunoz10** [comment]
Hi @elkarry, as of now our SDK works only for API 23 (Android 6) or greater. We haven't increased our minimumSDKVersion since we know some merchants targeting API Level 21 use our SDK. However, we recommend to add an if statement checking for the current Android version and handling the case by going through a different payment method, showing some error, etc...

An example would be something like this:

```
fun invokeCheckoutSdk() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            internalState.postValue(ViewState.CheckingOutInSdk)
            PayPalCheckout.startCheckout(
                CreateOrder { createOrderActions ->
                    if (isVaultFlow) {
                        createOrderActions.setVaultApprovalSessionId(currentToken)
                    } else {
                        createOrderActions.setBillingAgreementId(currentToken)
                    }
                }
            )
        } else {
            internalState.postValue(ViewState.MinSdkTooLow)
        }
    }
```

Let me know if you have any more questions!

**Comment by elkarry** [comment]
@ndmunoz10 Thanks for the answer.

Then this issue can be closed
